export type ProductStatus = 'In Stock' | 'Low Stock' | 'Out of Stock';

export type ProductRecord = {
  id: number;
  businessId: number;
  sku: string;
  barcode: string;
  productName: string;
  category: string;
  brand: string;
  supplier: string;
  currency: 'USD';
  unitCost: number;
  unitPrice: number;
  taxRate: number;
  discountRate: number;
  stockQuantity: number;
  reorderLevel: number;
  safetyStock: number;
  valuationMethod: 'FIFO' | 'Weighted Average';
  warehouse: string;
  cogsToDate: number;
  revenueToDate: number;
  lastPurchaseDate: string;
  lastSaleDate: string;
  status: ProductStatus;
};

export const productsByBusiness: Record<number, ProductRecord[]> = {
  1: [
    {
      id: 1,
      businessId: 1,
      sku: 'ACM-LTP-14PRO',
      barcode: '8901001123401',
      productName: 'ApexBook Pro 14',
      category: 'Computers',
      brand: 'Apex',
      supplier: 'Global Devices Ltd',
      currency: 'USD',
      unitCost: 980,
      unitPrice: 1299,
      taxRate: 18,
      discountRate: 4,
      stockQuantity: 36,
      reorderLevel: 12,
      safetyStock: 10,
      valuationMethod: 'FIFO',
      warehouse: 'Kigali Main WH',
      cogsToDate: 49000,
      revenueToDate: 67950,
      lastPurchaseDate: '2026-04-05',
      lastSaleDate: '2026-04-12',
      status: 'In Stock',
    },
    {
      id: 2,
      businessId: 1,
      sku: 'ACM-PHN-XR9',
      barcode: '8901001123402',
      productName: 'Orbit XR9 Phone',
      category: 'Mobile Devices',
      brand: 'Orbit',
      supplier: 'Eastwave Telecom Supply',
      currency: 'USD',
      unitCost: 420,
      unitPrice: 589,
      taxRate: 18,
      discountRate: 6,
      stockQuantity: 62,
      reorderLevel: 25,
      safetyStock: 18,
      valuationMethod: 'Weighted Average',
      warehouse: 'Kigali Main WH',
      cogsToDate: 31240,
      revenueToDate: 44380,
      lastPurchaseDate: '2026-04-03',
      lastSaleDate: '2026-04-11',
      status: 'In Stock',
    },
    {
      id: 3,
      businessId: 1,
      sku: 'ACM-TAB-A11',
      barcode: '8901001123403',
      productName: 'Nimbus Tab A11',
      category: 'Tablets',
      brand: 'Nimbus',
      supplier: 'Global Devices Ltd',
      currency: 'USD',
      unitCost: 260,
      unitPrice: 359,
      taxRate: 18,
      discountRate: 5,
      stockQuantity: 18,
      reorderLevel: 20,
      safetyStock: 15,
      valuationMethod: 'FIFO',
      warehouse: 'Kigali Main WH',
      cogsToDate: 14820,
      revenueToDate: 21480,
      lastPurchaseDate: '2026-03-29',
      lastSaleDate: '2026-04-10',
      status: 'Low Stock',
    },
    {
      id: 4,
      businessId: 1,
      sku: 'ACM-HDP-ANC',
      barcode: '8901001123404',
      productName: 'Pulse ANC Headphones',
      category: 'Audio',
      brand: 'Pulse',
      supplier: 'AcoustiCore Distribution',
      currency: 'USD',
      unitCost: 74,
      unitPrice: 119,
      taxRate: 18,
      discountRate: 8,
      stockQuantity: 120,
      reorderLevel: 40,
      safetyStock: 30,
      valuationMethod: 'Weighted Average',
      warehouse: 'Kigali Main WH',
      cogsToDate: 16280,
      revenueToDate: 27965,
      lastPurchaseDate: '2026-04-07',
      lastSaleDate: '2026-04-12',
      status: 'In Stock',
    },
    {
      id: 5,
      businessId: 1,
      sku: 'ACM-MON-27Q',
      barcode: '8901001123405',
      productName: 'Vertex 27Q Monitor',
      category: 'Displays',
      brand: 'Vertex',
      supplier: 'ClearView Tech Supplies',
      currency: 'USD',
      unitCost: 168,
      unitPrice: 249,
      taxRate: 18,
      discountRate: 3,
      stockQuantity: 41,
      reorderLevel: 18,
      safetyStock: 12,
      valuationMethod: 'FIFO',
      warehouse: 'Kigali Main WH',
      cogsToDate: 18920,
      revenueToDate: 28770,
      lastPurchaseDate: '2026-04-01',
      lastSaleDate: '2026-04-12',
      status: 'In Stock',
    },
    {
      id: 6,
      businessId: 1,
      sku: 'ACM-SSD-1TB',
      barcode: '8901001123406',
      productName: 'Quantum SSD 1TB',
      category: 'Storage',
      brand: 'Quantum',
      supplier: 'Bitware Components',
      currency: 'USD',
      unitCost: 92,
      unitPrice: 139,
      taxRate: 18,
      discountRate: 7,
      stockQuantity: 0,
      reorderLevel: 25,
      safetyStock: 20,
      valuationMethod: 'Weighted Average',
      warehouse: 'Kigali Main WH',
      cogsToDate: 22140,
      revenueToDate: 32980,
      lastPurchaseDate: '2026-03-10',
      lastSaleDate: '2026-04-08',
      status: 'Out of Stock',
    },
  ],
  3: [
    {
      id: 1,
      businessId: 3,
      sku: 'KIV-TIRE-18',
      barcode: '8901002123401',
      productName: 'RoadMaster Tire 18"',
      category: 'Vehicle Parts',
      brand: 'RoadMaster',
      supplier: 'Kivu Fleet Parts',
      currency: 'USD',
      unitCost: 88,
      unitPrice: 129,
      taxRate: 18,
      discountRate: 2,
      stockQuantity: 150,
      reorderLevel: 50,
      safetyStock: 36,
      valuationMethod: 'FIFO',
      warehouse: 'Rubavu Depot',
      cogsToDate: 25240,
      revenueToDate: 36980,
      lastPurchaseDate: '2026-04-04',
      lastSaleDate: '2026-04-12',
      status: 'In Stock',
    },
    {
      id: 2,
      businessId: 3,
      sku: 'KIV-OIL-20L',
      barcode: '8901002123402',
      productName: 'ProFleet Engine Oil 20L',
      category: 'Maintenance',
      brand: 'ProFleet',
      supplier: 'Rwanda Lubricants Co',
      currency: 'USD',
      unitCost: 54,
      unitPrice: 82,
      taxRate: 18,
      discountRate: 4,
      stockQuantity: 72,
      reorderLevel: 30,
      safetyStock: 22,
      valuationMethod: 'Weighted Average',
      warehouse: 'Rubavu Depot',
      cogsToDate: 17280,
      revenueToDate: 26340,
      lastPurchaseDate: '2026-04-02',
      lastSaleDate: '2026-04-11',
      status: 'In Stock',
    },
    {
      id: 3,
      businessId: 3,
      sku: 'KIV-BAT-24V',
      barcode: '8901002123403',
      productName: 'Dynacell 24V Battery',
      category: 'Electrical',
      brand: 'Dynacell',
      supplier: 'Kivu Fleet Parts',
      currency: 'USD',
      unitCost: 118,
      unitPrice: 169,
      taxRate: 18,
      discountRate: 3,
      stockQuantity: 22,
      reorderLevel: 25,
      safetyStock: 18,
      valuationMethod: 'FIFO',
      warehouse: 'Rubavu Depot',
      cogsToDate: 10990,
      revenueToDate: 15840,
      lastPurchaseDate: '2026-03-28',
      lastSaleDate: '2026-04-10',
      status: 'Low Stock',
    },
    {
      id: 4,
      businessId: 3,
      sku: 'KIV-PAD-HDX',
      barcode: '8901002123404',
      productName: 'Brake Pad HDX Set',
      category: 'Vehicle Parts',
      brand: 'HDX',
      supplier: 'Transit Spares East Africa',
      currency: 'USD',
      unitCost: 64,
      unitPrice: 96,
      taxRate: 18,
      discountRate: 5,
      stockQuantity: 0,
      reorderLevel: 28,
      safetyStock: 20,
      valuationMethod: 'Weighted Average',
      warehouse: 'Rubavu Depot',
      cogsToDate: 13760,
      revenueToDate: 21420,
      lastPurchaseDate: '2026-03-07',
      lastSaleDate: '2026-04-06',
      status: 'Out of Stock',
    },
    {
      id: 5,
      businessId: 3,
      sku: 'KIV-FLT-AIR',
      barcode: '8901002123405',
      productName: 'Air Filter XL',
      category: 'Maintenance',
      brand: 'AirGuard',
      supplier: 'Transit Spares East Africa',
      currency: 'USD',
      unitCost: 19,
      unitPrice: 33,
      taxRate: 18,
      discountRate: 0,
      stockQuantity: 110,
      reorderLevel: 40,
      safetyStock: 25,
      valuationMethod: 'FIFO',
      warehouse: 'Rubavu Depot',
      cogsToDate: 8420,
      revenueToDate: 13870,
      lastPurchaseDate: '2026-04-06',
      lastSaleDate: '2026-04-12',
      status: 'In Stock',
    },
    {
      id: 6,
      businessId: 3,
      sku: 'KIV-COOL-5L',
      barcode: '8901002123406',
      productName: 'Coolant Plus 5L',
      category: 'Maintenance',
      brand: 'Coolant Plus',
      supplier: 'Rwanda Lubricants Co',
      currency: 'USD',
      unitCost: 16,
      unitPrice: 27,
      taxRate: 18,
      discountRate: 0,
      stockQuantity: 210,
      reorderLevel: 70,
      safetyStock: 45,
      valuationMethod: 'Weighted Average',
      warehouse: 'Rubavu Depot',
      cogsToDate: 7340,
      revenueToDate: 12280,
      lastPurchaseDate: '2026-04-08',
      lastSaleDate: '2026-04-12',
      status: 'In Stock',
    },
  ],
};
